ALTER TABLE users DROP CONSTRAINT IF EXISTS users_status_check;
ALTER TABLE users
    ADD CONSTRAINT users_status_check
    CHECK (status IN ('ACTIVE', 'BLOCKED', 'PENDING_VERIFICATION'));
ALTER TABLE users ALTER COLUMN status SET DEFAULT 'PENDING_VERIFICATION';
