plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-amqp'
    implementation 'org.springframework.boot:spring-boot-starter-json'
    implementation 'software.amazon.awssdk:s3:2.29.52'
    implementation 'software.amazon.awssdk:url-connection-client:2.29.52'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
